### ISSUE TITLE
Review Comments 

### ISSUE THREAD

**Issue by ghost** [rizualam/Ascii#1]
1. Why stdlib is used when none of its functions are called
2. Why unsigned int is used when the max count is 126, you can use a char instead as it takes only 1 byte 
3. Why a while loop is used, where as this exactly fits the for loop (initialisation, comparison and increment)?

**Comment by rizualam** [comment]
#include <stdio.h>
int main(int argc, char *argv[])
{
    char a=0;
    for (a=0;a!=126;a++)
    {
    printf("%d=%c\n",a,a);
    }
    return 0;
}

**Comment by rizualam** [comment]
please check the above.

**Comment by ghost** [comment]
Good.
